# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Jcode-CP932
version:      0.08
version_from: lib/Jcode/CP932.pm
installdirs:  site
requires:
    B::Deparse:                    0
    Encode::EUCJPMS:               0.07
    Jcode:                         2
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
